services:
    knp_bundles.menu_builder:
        class: Knp\Bundle\KnpBundlesBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    acme_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: knp_bundles.menu_builder
        factory_method: createMainMenu
        arguments: ["@request", "@translator"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu