parameters:
    knp_bundles.updater.class: Knp\Bundle\KnpBundlesBundle\Updater\Updater
    knp_bundles.user.provider.class: Knp\Bundle\KnpBundlesBundle\Security\Core\User\UserProvider
    knp_bundles.trending_bundle_twitterer.class: Knp\Bundle\KnpBundlesBundle\Twitterer\TrendingBundleTwitterer
    knp_bundles.trending_bundle_tweet.template: "Discover {name}, today's trending #Symfony2 bundle {url} on #KnpBundles"
    knp_bundles.consumer.update_bundle.class: Knp\Bundle\KnpBundlesBundle\Consumer\UpdateBundleConsumer
    knp_bundles.consumer.github_hook.class: Knp\Bundle\KnpBundlesBundle\Consumer\GithubHookConsumer
    knp_bundles.user.manager.class: Knp\Bundle\KnpBundlesBundle\Entity\UserManager
    knp_bundles.output.class: Symfony\Component\Console\Output\NullOutput
    knp_bundles.travis.class: Knp\Bundle\KnpBundlesBundle\Travis\Travis
    knp_bundles.goutte.class: Goutte\Client
    knp_bundles.github.client.class: Github_Client
    knp_bundles.github.search.class: Knp\Bundle\KnpBundlesBundle\Github\Search
    knp_bundles.github.users.class: Knp\Bundle\KnpBundlesBundle\Github\User
    knp_bundles.git_repository_manager.class: Knp\Bundle\KnpBundlesBundle\Git\RepoManager
    knp_bundles.github.repository_api.class: Knp\Bundle\KnpBundlesBundle\Github\Repo
    knp_bundles.badge_generator.class: Knp\Bundle\KnpBundlesBundle\Badge\BadgeGenerator
    knp_bundles.imagine.gd.class: Imagine\Gd\Imagine
    knp_bundles.imagine.imagick.class: Imagine\Imagick\Imagine
    knp_bundles.imagine.gmagick.class: Imagine\Gmagick\Imagine
    knp_bundles.indexer.solr.class: Knp\Bundle\KnpBundlesBundle\Indexer\SolrIndexer
    knp_bundles.scoring.activity.class: Knp\Bundle\KnpBundlesBundle\Scoring\ActivityListener
    knp_bundles.scoring.composer.class: Knp\Bundle\KnpBundlesBundle\Scoring\ComposerListener
    knp_bundles.scoring.followers.class: Knp\Bundle\KnpBundlesBundle\Scoring\FollowersListener
    knp_bundles.scoring.knpbundles.class: Knp\Bundle\KnpBundlesBundle\Scoring\KnpBundlesListener
    knp_bundles.scoring.readme.class: Knp\Bundle\KnpBundlesBundle\Scoring\ReadmeListener
    knp_bundles.scoring.travis.class: Knp\Bundle\KnpBundlesBundle\Scoring\TravisListener

services:
    knp_bundles.updater:
        class: %knp_bundles.updater.class%
        arguments:
            - @knp_bundles.entity_manager
            - @knp_bundles.user.manager
            - @knp_bundles.github.search
            - @knp_bundles.github.users

    knp_bundles.user.manager:
        class: %knp_bundles.user.manager.class%
        arguments:
            - @knp_bundles.entity_manager

    knp_bundles.user.provider:
        class: %knp_bundles.user.provider.class%
        arguments:
            - @knp_bundles.user.manager

    knp_bundles.trending_bundle_twitterer:
        class: %knp_bundles.trending_bundle_twitterer.class%
        arguments:
            - @knp_bundles.entity_manager
            - %knp_bundles.trending_bundle_tweet.template%
            - @twitter_app

    knp_bundles.goutte:
        public: false
        class: %knp_bundles.goutte.class%

    knp_bundles.output:
        public: false
        class: %knp_bundles.output.class%

    knp_bundles.travis:
        class: %knp_bundles.travis.class%
        arguments:
            - @knp_bundles.output

    knp_bundles.github_client:
        public: false
        class: %knp_bundles.github.client.class%

    knp_bundles.git_repository_manager:
        class: %knp_bundles.git_repository_manager.class%
        arguments:
            - @filesystem
            - %knp_bundles.bundles_dir%
            - %knp_bundles.git_bin%

    knp_bundles.github_repository_api:
        class: %knp_bundles.github.repository_api.class%
        arguments:
          - @knp_bundles.github_client
          - @knp_bundles.output
          - @knp_bundles.git_repository_manager

    knp_bundles.github.search:
        class: %knp_bundles.github.search.class%
        arguments:
            - @knp_bundles.github_client
            - @knp_bundles.goutte
            - @knp_bundles.output

    knp_bundles.github.users:
        class: %knp_bundles.github.users.class%
        arguments:
            - @knp_bundles.github_client
            - @knp_bundles.output

    knp_bundles.indexer.solr:
        class: %knp_bundles.indexer.solr.class%
        arguments:
            - @doctrine
            - @solarium.client

    knp_bundles.consumer.update_bundle:
        class: %knp_bundles.consumer.update_bundle.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @knp_bundles.user.manager
            - @knp_bundles.github_repository_api
            - @knp_bundles.travis
            - @knp_bundles.indexer.solr
        calls:
            - [ setLogger, [@logger]]

    knp_bundles.imagine.gd:
        class: %knp_bundles.imagine.gd.class%
        public: false

    knp_bundles.imagine.imagick:
        class: %knp_bundles.imagine.imagick.class%
        public: false

    knp_bundles.imagine.gmagick:
        class: %knp_bundles.imagine.gmagick.class%
        public: false

    knp_bundles.badge_generator:
        class: %knp_bundles.badge_generator.class%
        arguments:
            - @knp_bundles.imagine
        calls:
            - [ setCacheDir, [%kernel.cache_dir%] ]

    knp_bundles.consumer.github_hook:
        public: false
        class: %knp_bundles.consumer.github_hook.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @old_sound_rabbit_mq.update_bundle_producer
        calls:
            - [ setLogger, [@logger]]

    knp_bundles.scoring.activity:
        class: %knp_bundles.scoring.activity.class%
        tags:
            - { name: kernel.event_listener, event: bundle.update_score, method: onScoreUpdate }

    knp_bundles.scoring.followers:
        class: %knp_bundles.scoring.followers.class%
        tags:
            - { name: kernel.event_listener, event: bundle.update_score, method: onScoreUpdate }

    knp_bundles.scoring.composer:
        class: %knp_bundles.scoring.composer.class%
        tags:
            - { name: kernel.event_listener, event: bundle.update_score, method: onScoreUpdate }

    knp_bundles.scoring.knpbundles:
        class: %knp_bundles.scoring.knpbundles.class%
        tags:
            - { name: kernel.event_listener, event: bundle.update_score, method: onScoreUpdate }

    knp_bundles.scoring.readme:
        class: %knp_bundles.scoring.readme.class%
        tags:
            - { name: kernel.event_listener, event: bundle.update_score, method: onScoreUpdate }

    knp_bundles.scoring.travis:
        class: %knp_bundles.scoring.travis.class%
        tags:
            - { name: kernel.event_listener, event: bundle.update_score, method: onScoreUpdate }
