imports:
    - { resource: parameters.yml }
    - { resource: @KnpBundlesBundle/Resources/config/security.yml }

framework:
    charset:          UTF-8
    csrf_protection:  true
    secret:           %secret%
    router:           { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:       { enabled: true, enable_annotations: true }
    templating:       { engines: ['twig'] }
    default_locale: en
    esi: { enabled: true }
    session:
        lifetime:       3600
        auto_start:     true
    translator:    { fallback: en }


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Markdown Configuration
knp_markdown:
    parser: ~       # Enable the parser service

# Time Configuration
knp_time: ~     # Enable the time helper

# Menu Configuration
knp_menu:
    twig: true

# Paginator Configuration
knp_paginator: ~

# KnpBundles Configuration
knp_bundles: ~

# Gravatar Configuration
ornicar_gravatar: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        path:     %database_path%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                  KnpBundlesBundle: ~

jms_i18n_routing:
    default_locale: en
    locales: [fr, pl, en]
    strategy: prefix_except_default

inori_twitter_app:
    file: %kernel.root_dir%/../vendor/twitteroauth/twitteroauth/twitteroauth.php
    consumer_key: %knp_bundles.twitter.consumer_key%
    consumer_secret: %knp_bundles.twitter.consumer_secret%
    oauth_token: %knp_bundles.twitter.oauth_token%
    oauth_token_secret: %knp_bundles.twitter.oauth_token_secret%

knp_zend_cache:
    templates:
        s2b_disqus:
            frontend:
                name: Core
                options:
                    lifetime: 600
                    automatic_serialization: true
            backend:
                name: File
                options:
                    cache_dir: %kernel.root_dir%/cache/%kernel.environment%

knp_disqus:
    api_key: %knp_bundles.disqus_key%
    forums:
        s2b:
            shortname: s2b
            cache:     s2b_disqus

old_sound_rabbit_mq:
    debug: %old_sound_rabbit_mq.debug%
    connections:
        default:
            host:      %old_sound_rabbit_mq.host%
            port:      %old_sound_rabbit_mq.port%
            user:      %old_sound_rabbit_mq.user%
            password:  %old_sound_rabbit_mq.password%
            vhost:     %old_sound_rabbit_mq.vhost%
    producers:
        update_bundle:
            connection: default
            exchange_options: {name: 'upload-bundle', type: direct, durable: true }
    consumers:
        update_bundle:
            connection: default
            exchange_options: {name: 'upload-bundle', type: direct, durable: true }
            queue_options:    {name: 'upload-bundle'}
            callback:         knp_bundles.consumer.update_bundle

nelmio_solarium:
    adapter:
        class: %solarium.adapter_class%
        host: %solarium.host%
        port: %solarium.port%
        path: %solarium.path%
