imports:
    - { resource: parameters.yml }
    - { resource: @KnpBundlesBundle/Resources/config/security.yml }

framework:
    charset:          UTF-8
    csrf_protection:  true
    secret:           %secret%
    router:           { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:       { enabled: true, enable_annotations: true }
    templating:       { engines: ['twig'] }
    default_locale: en
    session:
        lifetime:       3600
        auto_start:     true
    translator:    { fallback: en }


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Markdown Configuration
knp_markdown:
    parser: ~       # Enable the parser service

# Time Configuration
knp_time: ~     # Enable the time helper

# Menu Configuration
knp_menu:
    twig: true

# Paginator Configuration
knp_paginator:
    templating: ~

# KnpBundles Configuration
knp_bundles: ~

# Gravatar Configuration
ornicar_gravatar: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        path:     %database_path%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                  KnpBundlesBundle: ~

jms_i18n_routing:
    default_locale: en
    locales: [fr, pl, en]
    strategy: prefix_except_default
