imports:
    - { resource: config_prod.yml }

doctrine.dbal:
  default_connection:       default
  connections:
    default:
      driver:               PDOMySql
      dbname:               symfony2bundles
      user:                 ~
      password:             ~
      host:                 localhost
      port:                 ~
