parameters:
    kernel.include_core_classes: false

kernel.config:
    charset:             UTF-8
    error_handler_level: null

web.config:
    validation:
        enabled: true
    router: { resource: "%kernel.root_dir%/config/routing.yml" }

web.templating:
    escaping:       htmlspecialchars

markdown.parser: ~      # Enable the parser service

time.helper: ~      # Enable the time helper

menu.templating: ~

s2b.config: ~

doctrine.orm:
  default_entity_manager:   default
  cache_driver:             apc           # array, apc, memcache, xcache
  entity_managers:
    default:
      connection:           default

# doctrine.dbal:
#     dbname:   xxxxxxxx
#     user:     root
#     password: ~
# 
# doctrine.orm: ~
# 
# swift.mailer:
#     transport: gmail
#     username:  xxxxxxxx
#     password:  xxxxxxxx
